name: Build LaTeX document
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - images/
      - assetes/
      - beamerstatale.tex
      - beamerthemesintef.sty
      - sintefcolor.sty

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: beamerstatale.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: beamerstatale.pdf
      - name: Commit PDF to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add beamerstatale.pdf
          git commit -m "Auto-update PDF" || exit 0
          git push