name: Build LaTeX document
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - images/
      - assetes/
      - beamerstatale.tex
      - beamerthemesintef.sty
      - sintefcolor.sty
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: beamerstatale.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
